import { test, expect } from "@playwright/test";
import { mockApiRoutes, MOCK_VIDEO_ID } from "./mock-api";

const VIDEO_URL = `/video/${MOCK_VIDEO_ID}`;

test.describe("Responsive layout", () => {
  test.beforeEach(async ({ page }) => {
    await mockApiRoutes(page);
  });

  test("desktop watch page exposes the current primary workflow", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    await expect(
      page.getByRole("heading", { name: "Building APIs: Architecture and Best Practices", exact: true })
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Notes", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Summary", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Transcript", exact: true })).toBeVisible();
    await expect(page.getByText("Generated by Cap AI")).toBeVisible();
    await expect(page.getByRole("heading", { name: "Chapters", exact: true })).toBeVisible();
  });

  test("mobile watch page keeps the current content reachable", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(VIDEO_URL);
    await page.waitForLoadState("networkidle");

    await expect(page.getByRole("link", { name: "Cap4" })).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "Building APIs: Architecture and Best Practices", exact: true })
    ).toBeVisible();
    await expect(page.getByRole("button", { name: "Transcript", exact: true })).toBeVisible();

    await page.getByRole("button").nth(1).click();
    await expect(page.getByRole("link", { name: "Home" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Record" })).toBeVisible();
  });
});

test.describe("Home page", () => {
  test.beforeEach(async ({ page }) => {
    await mockApiRoutes(page);
  });

  test("home page renders provider status and the mocked library card", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/");
    await page.waitForLoadState("networkidle");

    await expect(page.getByRole("heading", { name: "Your Videos" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Library" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "System provider status" })).toBeVisible();
    await expect(page.getByText("Building APIs: Architecture and Best Practices")).toBeVisible();
  });
});
